In [1]:
from data_load import *

In [2]:
len(all_yks), len({yk for yk in all_yks if len(year_key2supercategories[yk]) > 0})

(11352, 11352)

In [2]:
len(cik2gvkey), len(gvkey2cik), len(all_yks)

(32197, 15386, 11352)

In [9]:
len(set(t['cik'])), len(set(t['gvkey']))

(32197, 55278)

We have 32197 uniques CIKs, but 55278 uniques GVKeys, yet in the file some CIKs do not have an associated GVKey, therefore there should be more CIK than GVkeys, not the other way around.

This means that there is at least one CIK that is mapped to multiple GVkeys. Let's find it :

In [10]:
c2g = {}
for i in t.index:
    cik = t['cik'][i]
    gvkey = t['gvkey'][i]
    try:
        if not (c2g[cik] == gvkey or (math.isnan(c2g[cik]) and math.isnan(gvkey))):
            print('Cik {} <-> {}, {} !!!'.format(cik, c2g[cik], gvkey))
    except KeyError:
        c2g[cik] = gvkey

In [15]:
len(set(gvkey2cik.values())), len(gvkey2cik)

(32197, 55278)

In [21]:
55278-32197

23081

In [18]:
len(set(gvkey2cik.keys()) - set(cik2gvkey.values()))

39892

In [20]:
l = list(set(gvkey2cik.keys()) - set(cik2gvkey.values()))
l[:100]

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [12]:
len(t.index)

145499

In [31]:
cik2gvkey[1576873]

nan

In [32]:
gvkey2cik = {(int(t['gvkey'][i]) if not math.isnan(t['gvkey'][i]) else float('NaN')):t['cik'][i] for i in t.index}

In [36]:
gvkey2cik[float('NaN')]

KeyError: nan

In [37]:
len(year_key2categories.items())

11569

In [2]:
[x for x in year_key2categories.items()][0:100]

[((1999, 64247, 12497), {308, 344}),
 ((1999, 838875, 30666), {208}),
 ((1999, 748580, 12110), {679}),
 ((1998, 910612, 29082), {679}),
 ((1998, 895659, 28494), {807}),
 ((1999, 719739, 17120), {602}),
 ((1999, 21828, 3184), {507}),
 ((1998, 789863, 12047), {245, 527, 614}),
 ((1999, 1039690, 65795), {171}),
 ((1999, 726514, 4274), {369}),
 ((1999, 1019265, 64198), {348, 382}),
 ((1998, 947116, 61247), {737}),
 ((1999, 26780, 3734), {371}),
 ((1999, 1013698, 63939), {633}),
 ((1999, 947661, 63572), {514, 581}),
 ((1999, 924140, 61397), {565}),
 ((1999, 10119, 2058), {382}),
 ((1998, 786765, 13193), {736, 753}),
 ((1998, 933141, 24466), {602}),
 ((1998, 824008, 19914), {737}),
 ((1998, 356213, 5671), {799}),
 ((1998, 351220, 2461), {581}),
 ((1999, 846729, 15302), {421}),
 ((1998, 887757, 28252), {804}),
 ((1998, 888919, 25877), {633, 641}),
 ((1999, 807863, 14113), {357}),
 ((1999, 848446, 11225), {306, 651}),
 ((1999, 50493, 12972), {202, 541, 651}),
 ((1998, 84567, 9195), {481, 506})

In [14]:
a = set([1,2,3])
b = set([3,4])
a |= b
a

{1, 2, 3, 4}